// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdP6IbAYCmtgy-fQYwsgPli-Gr3vfD0Vs',
    appId: '1:413394692252:web:6223f471d38b4e2b862559',
    messagingSenderId: '413394692252',
    projectId: 'krita-test',
    authDomain: 'krita-test.firebaseapp.com',
    storageBucket: 'krita-test.appspot.com',
    measurementId: 'G-L2796VS202',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlIbQI9H6TKxruP9nlnBv4EiBZtu0Sqpo',
    appId: '1:413394692252:android:5957253e3364777e862559',
    messagingSenderId: '413394692252',
    projectId: 'krita-test',
    storageBucket: 'krita-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMR6xlP4mldCjklEWnA9UpHR97QI8QNeM',
    appId: '1:413394692252:ios:8575e25c096933cd862559',
    messagingSenderId: '413394692252',
    projectId: 'krita-test',
    storageBucket: 'krita-test.appspot.com',
    androidClientId: '413394692252-grl2g65chst774j6rkdkogljqfdc14dr.apps.googleusercontent.com',
    iosClientId: '413394692252-hmi3uem8evbjeg0iso3ojv3pe7taq3fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.krita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMR6xlP4mldCjklEWnA9UpHR97QI8QNeM',
    appId: '1:413394692252:ios:8575e25c096933cd862559',
    messagingSenderId: '413394692252',
    projectId: 'krita-test',
    storageBucket: 'krita-test.appspot.com',
    androidClientId: '413394692252-grl2g65chst774j6rkdkogljqfdc14dr.apps.googleusercontent.com',
    iosClientId: '413394692252-hmi3uem8evbjeg0iso3ojv3pe7taq3fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.krita',
  );
}
